name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ubuntu:23.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install libgtk-4-dev
      run: sudo apt install -y libgtk-4-dev
    - name: install msgfmt
      run: sudo apt install -y msgfmt
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
